language: python
sudo: false
dist: bionic

addons:
  apt:
    packages:
     - python-pip
     - xsltproc
     - rfcdiff

install:
 - pip install xml2rfc idnits
 - gem install --no-doc kramdown-rfc2629

script:
 - make
 - make idnits
 - make issues || make issues DISABLE_ISSUE_FETCH=true && make gh-issues
 - make gh-pages

deploy:
  provider: script
  script: make upload
  skip_cleanup: true
  on:
    tags: true
